--overall churn rate
SELECT AVG(CHURN) AS churn_rate
FROM CHURN_DB.CHURN_SCHEMA.CHURN_DATA_NEW;

--Contract impact
SELECT 
  CONTRACT_ONE_YEAR,
  CONTRACT_TWO_YEAR,
  AVG(CHURN) AS churn_rate
FROM CHURN_DB.CHURN_SCHEMA.CHURN_DATA_NEW
GROUP BY 1,2;

--Payment method impact
SELECT 
  AVG(CHURN) AS churn_rate
FROM CHURN_DB.CHURN_SCHEMA.CHURN_DATA_NEW
WHERE PAYMENTMETHOD_ELECTRONIC_CHECK = 1;

--Tenure vs churn
SELECT 
  TENURE,
  AVG(CHURN) AS churn_rate
FROM CHURN_DB.CHURN_SCHEMA.CHURN_DATA_NEW
GROUP BY TENURE
ORDER BY TENURE;

--Charges impact
SELECT 
  CASE 
    WHEN MONTHLYCHARGES < 30 THEN 'Low'
    WHEN MONTHLYCHARGES BETWEEN 30 AND 70 THEN 'Medium'
    ELSE 'High'
  END AS charge_segment,
  AVG(CHURN) AS churn_rate
FROM CHURN_DB.CHURN_SCHEMA.CHURN_DATA_NEW
GROUP BY 1;


--Internet service impact
SELECT 
  INTERNETSERVICE_FIBER_OPTIC,
  INTERNETSERVICE_NO,
  AVG(CHURN) AS churn_rate
FROM CHURN_DB.CHURN_SCHEMA.CHURN_DATA_NEW
GROUP BY 1,2;